# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ranger-admin-service

  name: {{ include "myapp.fullname" . }}-ranger-service
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - name: "ranger-admin"
    port: 6080
    targetPort: 6080
  - name: "ranger-admin-ssl"
    port: 6182
    targetPort: 6182
  - name: "ranger-solr"
    port: 6083
    targetPort: 6083
  - name: "ranger-solr-ssl"
    port: 6183
    targetPort: 6183
  - name: "mariadb"
    port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ranger-admin-service

