---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project


# To run
#   * Ensure Docker is installed and running
#   * Start Egeria Platform stack using
#     'docker-compose -f ./egeria-platform.yaml up'
#
# Assumptions:
#   * Ports 9443 and 9092 are available on the host system - these are the default ports for Kafka and Egeria.
#   * by default, no external volumes are used - comments below give examples of using external volumes
#   * by default, Egeria will start with its set of default servers (active-metadata-store,view-server,
#     integration-daemon,engine-host,simple-metadata-store) - you can change this.
#   * by default, strict SSL validation is turned off
#
# See the following link for more info on volumes & why we need to use root:
#   https://docs.bitnami.com/containers/how-to/work-with-non-root-containers


services:
    kafka:
         image: 'bitnami/kafka:latest'
         ports:
             - '9092:9092'
         environment:
             - KAFKA_CFG_NODE_ID=0
             - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
             - KAFKA_CFG_PROCESS_ROLES=controller,broker
             - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
             - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
             - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
             - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    egeria-platform:
        depends_on:
            - kafka
        image: 'docker.io/odpi/egeria-platform:latest'
        ports:
            - '9443:9443'


        # Persistence
#        volumes:
#            - "YOUR DATA DIRECTORY"/data:/deployments/data
#            - "YOUR EXTRA LIBRARY DIRECTORY"/extra:/deployments/extra
#            - "ANOTHER DIRECTOR TO MOUNT"/:/deployments/user_mount


#
# Change external to true and create volumes manually if you wish to persist between runs
#
volumes:
    zookeeper-data:
        external: false
    kafka-data:
        external: false
