# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
jdkVersion = "17"
build = "./gradlew -x test -x javadoc  build"
jdkVersion = 17
build = "gradlew -x test -x javadoc  build"
