# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ui
  name: {{ .Release.Name }}-ui

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8443
      targetPort: 8443
      {{- if ( eq  .Values.service.type "NodePort" ) -}}
      nodePort: {{ .Values.service.nodeport.ui }}
      {{- end }}
  {{ if .Values.debug.egeriaJVM }}
    - name: debug
      port: 5005
      targetPort: 5005
      {{- if ( eq  .Values.service.type "NodePort" ) -}}
      nodePort: {{ .Values.service.nodeport.debug.ui }}
      {{- end }}
  {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ui

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ui
    spec:
      containers:
        - name: egeria
          image: "{{ if (.Values.image.egeria.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.egeria.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.egeria.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.egeria.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.egeria.name }}\
                  :{{ .Values.image.egeria.tag | default .Values.egeria.version }}"
          imagePullPolicy: {{ .Values.image.egeria.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
          ports:
            - containerPort: 8443
            {{ if .Values.debug.egeriaJVM }}
            - containerPort: 5005
            {{ end }}
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          resources: {}
          env:
            - name: "OMAS_SERVER_NAME"
              value: "cocoMDS4"
            - name: "OMAS_SERVER_URL"
              value: "https://{{ .Release.Name }}-datalake:9443"
            - name: "OPEN_LINEAGE_SERVER_URL"
              value: "https://{{ .Release.Name }}-datalake:9443"
            - name: "OPEN_LINEAGE_SERVER_NAME"
              value: "open-lineage"
            - name: "OPEN_LINEAGE_GRAPH_SOURCE"
              value: "MAIN"
            {{ if .Values.debug.egeriaJVM }}
            - name: JAVA_DEBUG
              value:  "true"
            {{ end }}
            - name: "JAVA_APP_JAR"
              value: "user-interface/ui-chassis-spring-{{ .Values.egeria.version}}.jar"
      restartPolicy: Always

status: {}
...
