# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: jupyter
  name: {{ .Release.Name }}-jupyter

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: 8888
      {{- if ( eq  .Values.service.type "NodePort" ) -}}
      nodePort: {{ .Values.service.nodeport.jupyter }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: jupyter
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-jupyter
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: jupyter

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: jupyter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: jupyter
    spec:
      securityContext:
        fsGroup: 100
      containers:
        - name: jupyter
          image: "{{ if (.Values.image.jupyter.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.jupyter.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.jupyter.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.jupyter.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.jupyter.name }}\
                  :{{ .Values.image.jupyter.tag | default .Values.egeria.version }}"
          imagePullPolicy: {{ .Values.image.jupyter.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
          args:
            - jupyter
            - lab
            - "--NotebookApp.token=''"
            - "--NotebookApp.iopub_data_rate_limit=1.0e10"
          env:
            - name: corePlatformURL
              value: "https://{{ .Release.Name }}-core:9443"
            - name: dataLakePlatformURL
              value: "https://{{ .Release.Name }}-datalake:9443"
            - name: devPlatformURL
              value: "https://{{ .Release.Name }}-dev:9443"
            - name: ctsPlatformURL
              value: "https://{{ .Release.Name }}-dev:9443"
            - name: factoryPlatformURL
              value: "https://{{ .Release.Name }}-factory:9443"
            - name: eventBusURLroot
              value: "{{ .Release.Name }}-kafka:9092"
            - name: uiExternalURL
              value: "{{ .Release.Name }}-nginx:443"
            - name: repositoryType
              value: {{ .Values.egeria.repositoryType}}
          ports:
            - containerPort: 8888
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          resources: {}
      restartPolicy: Always

status: {}
...
