# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
# Default values for ranger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  ranger:
    repository: planetf1/ranger-docker_ranger-admin
    tag: latest
    pullPolicy: IfNotPresent

  mariadb:
    repository: planetf1/ranger-docker_mariadb
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

# Network configuration
service:
  #LoadBalancer is another option (not for IBM Cloud free cluster)
  type: NodePort



