# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
name: vdc
description: Egeria VDC Environment 
version: 0.1.11
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - apache-ranger, ranger, security, odpi, egeria, open-metadata,vdc, virtualization
sources:
  - https://github.com/odpi/egeria
home: https://github.com/odpi/egeria
maintainers:
  - name: Nigel Jones
    email: nigel.l.jones+gh@gmail.com
