# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Egeria project.
blank_issues_enabled: true
contact_links:
  - name: Slack 
    url: https://slack.lfai.foundation
    about: Join the community here
