lineage-display-config:
  rules:
    invertEdge:
      - edgeType: SemanticAssignment
        destinationNodeType: GlossaryTerm
        sourceNodeType: GlossaryCategory
      - edgeType: TermCategorization
        destinationNodeType: GlossaryTerm
        sourceNodeType: GlossaryCategory
    primaryCategory:
      - edgeType: Classification
        sourceNodeType: GlossaryTerm
        destinationNodeType: PrimaryCategory
        classificationProperty: categoryQualifiedName
    removeNodes:
      - queriedNodeType: TabularColumn
        nodeTypesToRemove:
          - TabularSchemaType

