# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
# Default values for ranger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  ranger:
    repository: planetf1/ranger-admin-egeriavdc
    tag: 0.2.0
    pullPolicy: IfNotPresent

  mariadb:
    repository: planetf1/ranger-docker_mariadb
    tag: latest
    pullPolicy: IfNotPresent

  egeria:
    repository: planetf1/egeria-standalone
    tag: latest
    pullPolicy: IfNotPresent

  gaian:
    repository: planetf1/gaian
    tag: latest
    pullPolicy: IfNotPresent

  atlas:
    repository: planetf1/atlas-1773-egeria
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""


kafka:
  external:
    enabled: true
    type: LoadBalancer

