# SPDX-License-Identifier: Apache-2.0 
# Copyright Contributors to the Egeria project.
---
dependencies:
  - name: kafka
    version: 7.3.1
    repository: https://charts.bitnami.com/bitnami
    alias: egeriakafka
  - name: openldap
    version: 1.2.2
    repository: https://kubernetes-charts.storage.googleapis.com/
