---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  # General cluster configuration
  ATLAS_ENDPOINT: http://{{ include "myapp.fullname" . }}-atlas-service:21000
  EGERIA_ENDPOINT: http://{{ include "myapp.fullname" . }}-egeria-service:8080
  IGCPROXY_ENDPOINT: http://{{ include "myapp.fullname" . }}-ibm-igc-service:8080
{{ if .Values.kafka.internal.enabled }}
  KAFKA_ENDPOINT: {{ .Release.Name }}-cp-kafka:9092
{{ else }}
  KAFKA_ENDPOINT: {{ .Values.kafka.external.hostname }}:{{ .Values.kafka.external.port }}
{{ end }}
  EGERIA_USER: myuser
  EGERIA_COHORT: coco
  EGERIA_SERVER: myserver
  KAFKA_TOPIC: open-metadata.repository-services.cohort.coco.OMRSTopic
  # Used by IGC/Postgres & initialization
  STRICT_SSL: "false"
  LOGGING_LEVEL_ROOT: {{ .Values.logging.level }}
  POSTGRESQL_PASSWORD: passw0rd
  # Below values for IBMIGC need to reference either your container or external environment
  # See also: ibmigc... in values.yaml
{{ if .Values.ibmigc.internal.enabled }}
  IBMIGC_ENDPOINT: https://infosvr:9446
  IBMIGC_KAFKA_ENDPOINT: infosvr:59092
{{ else }}
  IBMIGC_ENDPOINT: https://{{ .Values.ibmigc.external.hostname }}:{{ .Values.ibmigc.external.port }}
  IBMIGC_KAFKA_ENDPOINT: {{ .Values.ibmigc.external.hostname }}:59092
{{ end }}
  IBMIGC_AUTH: aXNhZG1pbjppc2FkbWlu
  # Used by User Interface
  OMAS_SERVER_URL: http://{{ include "myapp.fullname" . }}-egeria-service:8080
  OMAS_SERVER_NAME: myserver
  GAIAN_HOST: {{ include "myapp.fullname" . }}-gaian-service
  LDAP_SERVER: {{ .Release.Name }}-openldap
  LDAP_PORT: {{ .Values.openldap.servicePort | quote }}
  LDAP_USER: cn=admin,dc=example,dc=org
  LDAP_PASS: {{ .Values.openldap.adminPassword | quote }}
