# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project

        {{ if eq .Values.service.cloud "IBMCloud" }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        helm.sh/chart: {{ include "myapp.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: ingress
    annotations:
        ingress.bluemix.net/tcp-ports: "serviceName={{ include "myapp.fullname" . }}-ranger-service ingressPort=6080 servicePort=6080;serviceName={{ include "myapp.fullname" . }}-atlas-service ingressPort=21000 servicePort=21000;serviceName={{ include "myapp.name" . }}-cp-kafka ingressPort=9092 servicePort=9092;serviceName={{ include "myapp.name" . }}-openldap ingressPort=389 servicePort=389;serviceName={{ include "myapp.fullname" . }}-egeria-service ingressPort=8080 servicePort=8080;serviceName={{ include "myapp.fullname" . }}-gaian-service ingressPort=6144 servicePort=6144;serviceName={{ include "myapp.fullname" . }}-igxproxy-service ingressPort=8090 servicePort=8080;serviceName={{ include "myapp.fullname" . }}-postgresql-service ingressPort=5432 servicePort=5432;serviceName={{ include "myapp.fullname" . }}-ui-service ingressPort=8443 servicePort=8443"

        #ingress.bluemix.net/rewrite-path: |
        #  serviceName={{ include "myapp.fullname" . }}-ranger-service rewrite=/;
        #  serviceName={{ include "myapp.fullname" . }}-atlas-service rewrite=/;

    name: {{ include "myapp.fullname" . }}-ingress

# We still have to create mappings here even if using the port mapping annotations, to keep k8s happy
# This applies even if they are not http applications due to the way the config is being overloaded
# via the additional annotatinos
spec:
    rules:
        - host: {{ .Values.service.ingress.externaldomain }}
          http:
              paths:
                  - path: /ranger
                    backend:
                        servicePort: 6080
                        serviceName: {{ include "myapp.fullname" . }}-ranger-service
                  - path: /atlas
                    backend:
                        servicePort: 21000
                        serviceName: {{ include "myapp.fullname" . }}-atlas-service
                  - path: /kafka
                    backend:
                        servicePort: 9082
                        serviceName: {{ include "myapp.fullname" . }}-cp-kafka
                  - path: /ldap
                    backend:
                        servicePort: 389
                        serviceName: {{ include "myapp.fullname" . }}-ldap
                  - path: /egeria
                    backend:
                        servicePort: 8080
                        serviceName: {{ include "myapp.fullname" . }}-egeria-service
                  - path: /gaian
                    backend:
                        servicePort: 6144
                        serviceName: {{ include "myapp.fullname" . }}-gaian-service
                  - path: /igcproxy
                    backend:
                        servicePort: 8080
                        serviceName: {{ include "myapp.fullname" . }}-igcproxy-service
                  - path: /postgresql
                    backend:
                        servicePort: 5432
                        serviceName: {{ include "myapp.fullname" . }}-postgresql-service
                  - path: /ui
                    backend:
                        servicePort: 8443
                        serviceName: {{ include "myapp.fullname" . }}-ui-service




{{ end }}
