# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: omrsmonitor-service

  name: {{ include "myapp.fullname" . }}-omrsmonitor-service

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 58080
      targetPort: 58080
      nodePort: {{ .Values.service.nodeport.omrsmonitor }}

  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: omrsmonitor-service
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-omrsmonitor
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: omrsmonitor-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: omrsmonitor-service

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: omrsmonitor-service

    spec:
      containers:
        - name: {{ include "myapp.fullname" . }}-omrsmonitor
          image: "{{ if (.Values.image.omrsmonitor.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.omrsmonitor.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.omrsmonitor.repository | default .Values.imageDefaults.repository) }}{{ .Values.image.omrsmonitor.repository | default .Values.imageDefaults.repository }}/{{ end }}\
                  {{ .Values.image.omrsmonitor.name }}\
                  :{{ .Values.image.omrsmonitor.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.omrsmonitor.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          ports:
            - containerPort: 58080
          resources: {}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
      restartPolicy: Always
status: {}
...
