# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ranger-admin-service
  name: {{ include "myapp.fullname" . }}-rangeradmin
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ranger-admin-service

  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ranger-admin-service

    spec:
      containers:
      - name: {{ .Chart.Name }}-ranger
        image: "{{ .Values.image.ranger.repository }}:{{ .Values.image.ranger.tag }}"
        ImagePullPolicy: "{{ .Values.image.ranger.pullPolicy }}"
        ports:
        - containerPort: 6080
        - containerPort: 6182
        - containerPort: 6083
        - containerPort: 6183
        - containerPort: 8886
        resources: {}
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin999
        image: "{{ .Values.image.mariadb.repository }}:{{ .Values.image.mariadb.tag }}"
        ImagePullPolicy: "{{ .Values.image.mariadb.pullPolicy }}"
        name: {{ .Chart.Name }}-mariadb
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
