# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
# TODO: swap to (if or .Values.solr.enabled .Values.ranger.enabled .Values.atlas.enabled) once embedded Solr migrated
{{ if .Values.solr.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: solr-service
  annotations:
  {{ if .Values.istio.enabled }}
  sidecar.istio.io/inject: "true"
  {{- end }}
  name: {{ include "myapp.fullname" . }}-solr-service

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8983
      targetPort: 8983
      nodePort: {{ .Values.service.nodeport.solr }}
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: solr-service
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-solr
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: solr-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: solr-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: solr-service
    spec:
      containers:
        - name: solr
          image: "{{ if (.Values.image.solr.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.solr.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.solr.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.solr.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.solr.name }}\
                  :{{ .Values.image.solr.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.solr.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          ports:
            - containerPort: 8983
          resources: {}
      restartPolicy: Always

status: {}
{{ end }}
