# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
{{ if .Values.atlas.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: atlas-service
  annotations:
    {{ if .Values.istio.enabled }}
    sidecar.istio.io/inject: "true"
    {{- end }}
  name: {{ include "myapp.fullname" . }}-atlas-service

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: 9443
      targetPort: 9443
      nodePort: {{ .Values.service.nodeport.atlasproxy }}
    - name: web
      port: 21000
      targetPort: 21000
      nodePort: {{ .Values.service.nodeport.atlas }}
    - name: kafka
      port: 9027
      targetPort: 9027
      nodePort: {{ .Values.service.nodeport.atlas_kafka }}
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: atlas-service
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ include "myapp.fullname" . }}-atlas
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: atlas-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: atlas-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "myapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: atlas-service
    spec:
      # Fix the hostname to what the image requires of itself
      hostname: atlas
      volumes:
        - name: egeria-connector-volume
          emptyDir: {}
      initContainers:
        - name: init-connector
          image: "{{ if (.Values.image.configure.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.configure.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.configure.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.configure.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.configure.name }}\
                  :{{ .Values.image.configure.tag | default .Values.egeria.version }}"
          imagePullPolicy: {{ .Values.image.configure.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
          command:
            - "/bin/bash"
            - "-c"
            - >
                cd /opt/egeria/connectors &&
                wget ${EGERIA_ARTIFACTORY_RELEASE}/${ATLAS_CONNECTOR_URL_PATH}/${ATLAS_CONNECTOR_VERSION}/egeria-connector-hadoop-ecosystem-package-${ATLAS_CONNECTOR_VERSION}-jar-with-dependencies.jar && touch RELEASE;

                if [ $? -ne 0 ]; then wget ${EGERIA_ARTIFACTORY_STAGING}/${ATLAS_CONNECTOR_URL_PATH}/${ATLAS_CONNECTOR_VERSION}/egeria-connector-hadoop-ecosystem-package-${ATLAS_CONNECTOR_VERSION}-jar-with-dependencies.jar && touch STAGING; fi;
                if [ $? -ne 0 ]; then wget ${EGERIA_ARTIFACTORY_SNAPSHOT}/${ATLAS_CONNECTOR_URL_PATH}/${ATLAS_CONNECTOR_VERSION}/egeria-connector-hadoop-ecosystem-package-${ATLAS_CONNECTOR_VERSION}-jar-with-dependencies.jar && touch SNAPSHOT; fi;
                if [ $? -ne 0 ]; then wget ${EGERIA_ARTIFACTORY_SNAPSHOT}/${ATLAS_CONNECTOR_URL_PATH}/${ATLAS_CONNECTOR_VERSION}-SNAPSHOT/egeria-connector-atlas-package-${ATLAS_CONNECTOR_VERSION}-SNAPSHOT-jar-with-dependencies.jar && touch SNAPSHOT; fi
          volumeMounts:
            - mountPath: /opt/egeria/connectors
              name: egeria-connector-volume
      containers:
        - name: proxy
          image: "{{ if (.Values.image.egeria.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.egeria.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.egeria.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.egeria.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.egeria.name }}\
                  :{{ .Values.image.egeria.tag | default .Values.egeria.version }}"
          imagePullPolicy: {{ .Values.image.egeria.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
          env:
            - name: "LOADER_PATH"
              value: "/opt/egeria/connectors"
          ports:
            - containerPort: 9443
          readinessProbe:
            tcpSocket:
              port: 9443
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          resources: {}
          volumeMounts:
            - mountPath: /opt/egeria/connectors
              name: egeria-connector-volume
              readOnly: true
        - name: apache-atlas
          image: "{{ if (.Values.image.atlas.registry | default .Values.imageDefaults.registry) }}{{ .Values.image.atlas.registry | default .Values.imageDefaults.registry }}/{{ end }}\
                  {{ if (.Values.image.atlas.namespace | default .Values.imageDefaults.namespace) }}{{ .Values.image.atlas.namespace | default .Values.imageDefaults.namespace }}/{{ end }}\
                  {{ .Values.image.atlas.name }}\
                  :{{ .Values.image.atlas.tag | default .Values.imageDefaults.tag }}"
          imagePullPolicy: {{ .Values.image.atlas.pullPolicy | default .Values.imageDefaults.pullPolicy }}
          ports:
            - containerPort: 21000
          livenessProbe:
            httpGet:
              path: /login.jsp
              port: 21000
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /login.jsp
              port: 21000
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources: {}
          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-configmap
          env:
            - name: "ATLAS_OPTS"
              value: '-Dkafka.advertised.hostname={{ include "myapp.fullname" . }}-atlas-service'
      restartPolicy: Always

status: {}
{{ end }}
