# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  # General cluster configuration - for core egeria, kafka - these must be used
  EGERIA_USER: {{ .Values.egeria.user }}
  EGERIA_COHORT: {{ .Values.egeria.cohort }}
  EGERIA_SERVER: {{ .Values.egeria.server }}
  # Used by IGC/Postgres & initialization
  STRICT_SSL: "false"
  LOGGING_LEVEL_ROOT: {{ .Values.logging.level }}
  EGERIA_ENDPOINT: http://{{ include "myapp.fullname" . }}-egeria-service:8080

  {{ if .Values.kafka.internal.enabled }}
  KAFKA_ENDPOINT: {{ .Release.Name }}-egeriakafka:9092
  {{ else }}
  # If using external kafka this is typically a comma seperated list of brokers
  # It is also likely insufficient to connect without additional authentication information
  KAFKA_ENDPOINT: {{ .Values.kafka.external.brokers }}
  {{ end }}

  {{ if .Values.atlas.enabled }}
  ATLASPROXY_ENDPOINT: http://{{ include "myapp.fullname" . }}-atlas-service:8080
  ATLAS_HOST: {{ include "myapp.fullname" . }}-atlas-service
  ATLAS_PORT: "21000"
  ATLAS_ENDPOINT: http://{{ include "myapp.fullname" . }}-atlas-service:21000
  ATLAS_SERVER: {{ .Values.atlas.proxyserver }}
  ATLAS_USER: {{ .Values.atlas.user }}
  ATLAS_PASS: {{ .Values.atlas.password }}
  ATLAS_KAFKA_ENDPOINT: {{ include "myapp.fullname" . }}-atlas-service:9027
  ATLAS_CONNECTOR_URL: https://odpi.jfrog.io/odpi/egeria-{{ .Values.connectors.repo }}-local/org/odpi/egeria/egeria-connector-apache-atlas-package/{{ .Values.connectors.version }}/egeria-connector-apache-atlas-package-{{ .Values.connectors.version }}-jar-with-dependencies.jar
  {{ end }}

  {{ if or .Values.postgresql.enabled .Values.ranger.enabled }}
  POSTGRESQL_PASSWORD: passw0rd
  {{ end }}

  {{ if .Values.ranger.enabled }}
  RANGER_PASSWORD: admin999
  {{ end }}

  {{ if .Values.ibmigc.enabled }}
  IGCPROXY_ENDPOINT: http://{{ include "myapp.fullname" . }}-ibm-igc-service:8080
  # Below values for IBMIGC need to reference either your container or external environment
  # See also: ibmigc... in values.yaml
  {{ if .Values.ibmigc.internal.enabled }}
  IBMIGC_HOST: infosvr
  IBMIGC_PORT: "9446"
  IBMIGC_KAFKA_ENDPOINT: infosvr:59092
  {{ else }}
  IBMIGC_HOST: {{ .Values.ibmigc.external.hostname }}
  IBMIGC_PORT: "{{ .Values.ibmigc.external.ports.https }}"
  IBMIGC_KAFKA_ENDPOINT: {{ .Values.ibmigc.external.hostname }}:{{ .Values.ibmigc.external.ports.broker }}
  {{ end }}
  IBMIGC_USER: {{ .Values.ibmigc.user }}
  IBMIGC_PASS: {{ .Values.ibmigc.password }}
  IBMIGC_SERVER: {{ .Values.ibmigc.proxyserver }}
  IBMIGC_CONNECTOR_URL: https://odpi.jfrog.io/odpi/egeria-{{ .Values.connectors.repo }}-local/org/odpi/egeria/egeria-connector-ibm-information-server-package/{{ .Values.connectors.version }}/egeria-connector-ibm-information-server-package-{{ .Values.connectors.version }}-jar-with-dependencies.jar
  {{ end }}

  # Used by User Interface
  {{ if .Values.ui.enabled }}
  OMAS_SERVER_URL: http://{{ include "myapp.fullname" . }}-egeria-service:8080
  OMAS_SERVER_NAME: myserver
  {{ end }}

  {{ if .Values.gaian.enabled }}
  GAIAN_HOST: {{ include "myapp.fullname" . }}-gaian-service
  {{ end }}

  {{ if .Values.openldap.enabled }}
  LDAP_SERVER: {{ .Release.Name }}-openldap
  LDAP_PORT: {{ .Values.openldap.servicePort | quote }}
  LDAP_USER: cn=admin,dc=example,dc=org
  LDAP_PASS: {{ .Values.openldap.adminPassword | quote }}
  {{ end }}
