# <!-- SPDX-License-Identifier: Apache-2.0 -->
# Copyright Contributors to the Egeria project.
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: egeria-service

  name: egeria

spec:
  type: NodePort
  ports:
  - name: "egeria"
    port: 8080
    targetPort: 8080

  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: egeria-service


