# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
---
pr: none

trigger:
  batch: true
  branches:
    include:
      - master
      - egeria-release-*

schedules:
  - cron: "0 11 * * 6"
    displayName: Weekly CLM Scan
    always: true
    branches:
      include:
        - master
        - egeria-release-*

variables:
  - group: Artifactory
  - group: NexusIQ
  - name: CLM_VERSION
    value: '2.8.1-01'

stages:
  - stage: CLM
    jobs:
      - job: Scan
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              goals: "clean install"
              options: >-
                  --batch-mode
                  -e
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              goals: "dependency:tree com.sonatype.clm:clm-maven-plugin:$(CLM_VERSION):evaluate"
              options: >-
                  --batch-mode
                  -e
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
                  -Dclm.stage="build"
                  -Dclm.applicationId="$(Nexus.IQ.AppId)"
                  -Dclm.serverUrl="$(Nexus.IQ.Server)"
                  -Dclm.username="$(Nexus.IQ.User)"
                  -Dclm.password="$(Nexus.IQ.Pass)"
