# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Maven Build"

on:
  pull_request:
    branches: [master, feature-*, egeria-release-*]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Maven Java 11"
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-java11-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-java11
      - name: Build with Maven
        run: mvn -DargLine="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:GCTimeRatio=99" -B clean verify --file pom.xml
      - name: Upload assemblies
        uses: actions/upload-artifact@v2
        with:
          name: Assemblies
          path: open-metadata-distribution/open-metadata-assemblies/target/*.gz
