# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Publish JavaDoc"

# Trigger after code is merged. only on main repo
# - does not run on modification (may be just text)

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    runs-on: ubuntu-latest
    name: "Javadoc"
    if: startsWith(github.repository,'odpi/')
    steps:
      - uses: actions/checkout@v3
        name: Checkout source
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/main'}}
      - uses: gradle/wrapper-validation-action@v1
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/main'}}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # Build first - lombok & other pre-processing may be needed. safer...
      - name: build
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/main'}}
        run: './gradlew -x test -x javadoc'
      - name: javadoc
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/main'}}
        run: './gradlew aggregateJavadoc'
      - name: publish
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/main'}}
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: build/docs/javadoc
      - name: Upload Log of any dependency failures
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/main'}}
        uses: actions/upload-artifact@v3
        with:
          name: Dependency Analysis Report (on failure)
          path: build/reports/dependency-analysis/build-health-report.txt
          if-no-files-found: ignore
