# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Merge master)"

# Trigger after code is merged. only on main repo
# - does not run on modification (may be just text)

on:
  push:
    branches: [master,egeria-release-*,feature-*]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Merge master"
    steps:
      - uses: actions/checkout@v2
        name: Checkout source
        # Only for a merge
        if: ${{ github.event_name == 'push' && github.repository == 'odpi/egeria' }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          # Java 11 is used for merge builds (PRs do check Java latest)
          java-version: '11'
          distribution: 'adopt'
          # Publishing attributes for maven central (this step adds to setting.xml)
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Keys must be known to maven central - require broad publishing
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # Build and publish - but only for master
      - name: Build with Maven (Publish snapshots to maven central + docker)
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/master'}}
        # See https://github.com/actions/toolkit/issues/231 requires parms using . to be quoted
        run: 'mvn -B -DuseMavenCentral clean deploy'
        # Needed for publishing -- note we push to a staging area, login to oss.sonatype.org to 
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          # Build and publish - but only for master
      - name: Build with Maven (no snapshots / docker published)
        if: ${{ github.repository != 'odpi/egeria' || github.ref != 'refs/heads/master'}}
        run: mvn -B clean verify
      # --
      # TODO - Publish docker images
      # Prep for docker builds which are currently done as part of the maven build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to container registry (Quay.io)
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_ACCESS_TOKEN }}
      # Build and publish - but only for master
      - name: Build with Maven (Publish snapshots to maven central + docker)
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/master'}}
        # See https://github.com/actions/toolkit/issues/231 requires parms using . to be quoted
        run: 'cd open-metadata-resources/open-metadata-deployment/docker && mvn -B -DuseMavenCentral -Ddocker "-Ddocker.taglatest" "-Ddocker.repo=odpi" "-Ddocker.registry=docker.io" "-Ddocker.images=core" clean deploy'
        # Needed for publishing -- note we push to a staging area, login to oss.sonatype.org to
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - name: Login to container registry (Docker Hub)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Build and publish - but only for master
      - name: Build with Maven (Publish snapshots to maven central + docker)
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/master'}}
        # See https://github.com/actions/toolkit/issues/231 requires parms using . to be quoted
        run: 'cd open-metadata-resources/open-metadata-deployment/docker && mvn -B -DuseMavenCentral -Ddocker "-Ddocker.taglatest" "-Ddocker.repo=odpi" "-Ddocker.registry=docker.io" "-Ddocker.images=core" clean deploy'
        # Needed for publishing -- note we push to a staging area, login to oss.sonatype.org to
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      # --
      # Mostly for verification - not published to the release itself for now
      - name: Upload assemblies
        uses: actions/upload-artifact@v2
        with:
          name: Assemblies
          path: open-metadata-distribution/open-metadata-assemblies/target/*.gz
