# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Publish JavaDoc"

# Trigger after code is merged. only on main repo
# - does not run on modification (may be just text)

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    runs-on: ubuntu-latest
    name: "Javadoc"
    steps:
      - uses: actions/checkout@v2
        name: Checkout source
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/master'}}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      # Build first - lombok & other pre-processing may be needed. safer...
      - name: build
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/master'}}
        run: './gradlew -x test -x javadoc'
      - name: javadoc
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/master'}}
        run: './gradlew aggregateJavadoc'
      - name: publish
        if: ${{ github.repository == 'odpi/egeria' && github.ref == 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build/docs/javadoc
