# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Gradle"

on:
  pull_request:
    branches: [master, feature-*, egeria-release-*]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Gradle"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v3.0.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        # For a build machine environment, force a more clean build 
        run: ./gradlew clean build --no-build-cache --no-configure-on-demand --priority normal --no-watch-fs --refresh-dependencies
      - name: Upload Test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: Jacoco Coverage Report
          path: build/reports/jacoco/codeCoverageReport

