# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Windows Daily Build (java11, maven)"

on:
  # Scheduled actions always occur on the default branch (master) only
  # Allow on-demand verification in case issues reported with a recent change in master during the day
  # or for verifying other branches manually
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    

jobs:
  build:
    runs-on: windows-latest
    name: "Maven Java 11"
    steps:
      # We'll run Java 11 here
      - name: setup git to use long paths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v2
        name: Checkout
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-daily-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-daily
      # Windows is slow for IO. Source/javadoc well verified elsewhere so we skip those here:
      - name: Build with Maven
        run: mvn clean verify 
      # no assemblies being uploaded here - we just want to verify